global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['34.125.78.102:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['34.125.78.102:9100']

  - job_name: 'kafka'
    static_configs:
      - targets: ['34.125.78.102:7070']

  - job_name: 'kafka-server'
    static_configs:
      - targets: ['10.182.0.2:9092']

  - job_name: 'kafka-server-tls'
    static_configs:
      - targets: ['10.182.0.2:9093']
    tls_config:
      insecure_skip_verify: true
      ca_file: /data/certs/truststore.jks
      cert_file: /data/certs/keystore.jks
      key_file: /data/certs/keystore.jks
